Countries = (
    ('Afghanistan','Afghanistan'),
    ('Albania','Albania'),
    ('Algeria','Algeria'),
    ('Andorra','Andorra'),
    ('Angola','Angola'),
    ('Austria','Austria'),
    ('Bahrain','Bahrain'),
    ('Belgium','Belgium'),
    ('Bolivia','Bolivia'),
    ('Botswana','Botswana'),
    ('Burundi','Burundi'),
    ('Croatia','Croatia'),
    ('Cyprus','Cyprus'),
    ('Czech Republic','Czech Republic'),
    ('Denmark','Denmark'),
    ('Djibouti','Djibouti'),
    ('Egypt','Egypt'),
    ('Ethiopia','Ethiopia'),
    ('Finland','Finland'),
    ('France','France'),
    ('Gabon','Gabon'),
    ('United Kingdom','United Kingdom'),
    ('Gambia','Gambia'),
    ('Georgia','Georgia'),
    ('Germany','Germany'),
    ('Ghana','Ghana'),
    ('Greece','Greece'),
    ('Guinea','Guinea'),
    ('Hungary','Hungary'),
    ('Iceland','Iceland'),
    ('Ireland','Ireland'),
    ('Israel','Israel'),
    ('Isle of','Isle of'),
    ('Italy','Italy'),
    ('Jordan','Jordan'),
    ('Kenya','Kenya'),
    ('Kuwait','Kuwait'),
    ('Lebanon','Lebanon'),
    ('Lesotho','Lesotho'),
    ('Liberia','Liberia'),
    ('Liechtenstein','Liechtenstein'),
    ('Lithuania','Lithuania'),
    ('Luxembourg','Luxembourg'),
    ('Macao','Macao'),
    ('Madagascar','Madagascar'),
    ('Malawi','Malawi'),
    ('Malaysia','Malaysia'),
    ('Maldives','Maldives'),
    ('Mali','Mali'),
    ('Malta','Malta'),
    ('Martinique','Martinique'),
    ('Mauritania','Mauritania'),
    ('Mauritius','Mauritius'),
    ('Mayotte','Mayotte'),
    ('Morocco','Morocco'),
    ('Mozambique','Mozambique'),
    ('Namibia','Namibia'),
    ('Nauru','Nauru'),
    ('Nepal','Nepal'),
    ('Netherlands','Netherlands'),
    ('Nicaragua','Nicaragua'),
    ('Niger','Niger'),
    ('Nigeria','Nigeria'),
    ('Norway','Norway'),
    ('Oman','Oman'),
    ('Pakistan','Pakistan'),
    ('Philippines','Philippines'),
    ('Poland','Poland'),
    ('Portugal','Portugal'),
    ('Puerto Rico','Puerto Rico'),
    ('Qatar','Qatar'),
    ('Reunion','Reunion'),
    ('Romania','Romania'),
    ('Rwanda','Rwanda'),
    ('Saudi Arabia','Saudi Arabia'),
    ('Senegal','Senegal'),
    ('Serbia','Serbia'),
    ('Russia','Russia'),
    ('Seychelles','Seychelles'),
    ('Sierra Leone','Sierra Leone'),
    ('Slovakia','Slovakia'),
    ('Slovenia','Slovenia'),
    ('Somalia','Somalia'),
    ('South Africa','South Africa'),
    ('Spain','Spain'),
    ('Sri Lanka','Sri Lanka'),
    ('Sudan','Sudan'),
    ('Swaziland','Swaziland'),
    ('Sweden','Sweden'),
    ('Switzerland','Switzerland'),
    ('Tonga','Tonga'),
    ('Tunisia','Tunisia'),
    ('Turkey','Turkey'),
    ('Uganda','Uganda'),
    ('Ukraine','Ukraine'),
    ('United Arab','United Arab'),
    ('Yemen','Yemen'),
    ('Zambia','Zambia'),
    ('Zimbabwe','Zimbabwe'),
)

Location = (
	('EDC', 'EDC Zaltbommel'),
	('CUSTOMER', 'Customer Premises'),
)
Status = (
    ('OPEN UNALLOCATED', 'Open Unallocated'),
    ('OPEN ALLOCATED', 'Open Allocated'),
    ('SUCCESSFUL', 'Successful'),
    ('UNSUCCESSFUL', 'Unsuccessful'),
    ('CANCELLED', 'Cancelled'),
)
Services_required = (
	('YES', 'Yes'),
	('NO', 'No'),
)
