# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-20 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offering_request', '0003_auto_20161020_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering_request',
            name='request_date',
            field=models.DateField(),
        ),
    ]
