# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offering_request', '0007_auto_20161029_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offering_request',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offering_request.Offering'),
        ),
    ]
